- .gitignore
- fstab.yaml
> chore: Configure SharePoint instance

- scripts.js
encapsulating readout of block config
> refactor: improved metadata handling

- footer.md
- head.html
- header.md
- hub/scripts.js
Fixes https://github.com/adobe/fedpub/issues/14
> feat: Integrate FEDS library

- .eslintrc.js
- hub/scripts.js
- hub/scripts.js.old
- hub/styles.css
A separate `code-modularization` branch has been created, where all resources are spread in modules, which then get automatically compiled. The result of that compilation needs to be ported to the `master` branch as well, so we can reach functionality and approach parity and to aid in benchmark testing.
A quick summary of other changes:
* theme3 styles have been implemented as per the guidelines from https://spectrum.adobe.com/;
* the `.eslintrc.js` config file has been updated to accept frequently used global variables;
* the JS logic has been updated to a IIFE structure to avoid exposing everything to the global namespace;
* the previous `scripts.js` file has been moved in its original form to `hub/scripts.js.old` for quick referencing purposes;
https://github.com/adobe/fedpub/issues/16 …
> Port JS logic and CSS styles from modularization branch

- hub/scripts.js
Implement Adobe Launch; add support for analytics
Locally
> feat(analytics): Implement Launch

- head.html
Sync changes introduced by https://github.com/adobe/fedpub/pull/35
> Load fonts from Typekit

- hub/styles.css
The styles implemented until now have been mostly inspired by the Spectrum library. However, it seems there are slight differences in those specs when compared to the Theme3 typography styles. This PR aims to bring the styles closer to the Theme3 specs.
https://github.com/adobe/fedpub/issues/37
The Studio team is still reviewing the styles to suggest some minor changes to be on par with the Theme3 specs.
Locally, no major impact should occur, as this only touches on styles.
> Adapt Spectrum styles to Theme3 guidelines

- hub/taxonomy.js
- hub/tools/tagger.js
* Handle fetch errors
* Add a space before each tag when copying to clipboard
> Tagger enhancements

- hub/scripts.js
FEDS library will be configured to load a different experience based on the article section. FEDS will take care of finding the best experience if the configured one is not available.
> Load a different navigation based on article section

- 404.html
> add 404 redirect

- hub/scripts.js
Set a different client_id based on the article cloud; this will enable retrieving personalization data.
In the browser, using breakpoints to change the client_id and locally.
> Set client_id based on article cloud

- tools/sidekick/plugins.js
> feat(sidekick): delegate window mangement to browser/user

- tools/sidekick/plugins.js
See https://github.com/adobe/helix-pages/issues/847
> feat(sidekick): prep for env switcher

- tools/translation/ui.js
Localisation team's feedback: extra buttons are useless.
> feat(translation): remove confusing buttons

- hub/scripts/scripts.js
Fixes a CSS issue in the footer
https://css-fix--fedpub--adobe.hlx.live/de/documentcloud/acrobat/hub/how-to/how-to-compress-pdfs-android
Restored the behavior on the left picture. The bug was causing the footer 'cookie preferences' to look like on the right picture
> Remove the footerLinkSelector from privacy

- hub/taxonomy.js
- tools/sidekick/config.js
https://fiixes--fedpub--adobe.hlx3.page/documentcloud/sign/hub/document-types/invoice-vs-receipt
> fix: tagger issues

- helix-query.yaml
- remove obsolete properties
- simplify target
> Remove extension from index

- hub/scripts/scripts.js
Load the new Privacy component through FEDS without delay
https://new-privacy2--fedpub--adobe.hlx3.page/it/sign/hub/document-types/invoice-vs-receipt#
The new Privacy component is now available.
locally
> Load new Privacy through FEDS

- tools/sidekick/config.js
- tools/translation/config.js
- tools/translation/tracker.js
- tools/translation/ui.js
Minor required changes to be hlx3 compliant.
> chore: migrate translation tool to hlx3

- hub/scripts/scripts.js
https://martech--fedpub--adobe.hlx3.page/it/sign/hub/document-types/invoice-vs-receipt
> Load Martech as soon as possible

- helix-sitemap.yaml
SEO team requested sitemaps to be generated using `lang-country` hreflang format.
https://sitemap-update--fedpub--adobe.hlx3.page/it/sign/hub/document-types/invoice-vs-receipt
> update sitemap properties

- helix-sitemap.yaml
Last step in implementing automated sitemaps. The changes will replace the manual sitemaps with automated versions.
> update sitemap path

- hub/scripts/scripts.js
- package-lock.json
The current martech implementation is not optimized for performance.  We have worked hard as a team to come up with a new optimized approach using the new AEP Web SDK that should improve performance dramatically without compromising on data or analytics.
Test:
https://bbythewa--fedpub--adobe.hlx3.page/it/sign/hub/document-types/invoice-vs-receipt?alloy=on
none
Performance improvements.
Tested on my local branch.
> chore: Alloy optimized implementation.

- 404.html
> 404img fix

- hub/styles/styles.css
Resolving Issue: [MWPW-112551](https://jira.corp.adobe.com/browse/MWPW-112551)
Before: https://main--fedpub--adobe.hlx.page/kr/acrobat/hub/how-to/add-hyperlink-to-pdf
After: https://responsive-img--fedpub--adobe.hlx.page/kr/acrobat/hub/how-to/add-hyperlink-to-pdf
> Set responsive image.
