hub/styles.css
FEDS navigation uses the font family set at body level; the proper value - `adobe-clean` - needs to be set.
Fixes #22
=> fix(page): Set font-family property on body tag

hub/scripts.js, hub/styles.css
This addresses styling updates, namely:
* implements Spectrum CTA styles for primary and secondary buttons;
* updates the FOUC strategy to initially hide just tables that require conversion. As soon as the decorations occur, those items will either have been transformed to a component with its own styling rules OR, if it doesn't require any transformation, the table will be shown with the default styles.
https://github.com/adobe/fedpub/issues/18
* Studio team requires particular styling for certain elements;
* The FOUC strategy has an impact on perceived performance, since it can be tied to the first contentful paint metric.
Locally:
* ensuring the styles of the CTA buttons are correctly applied;
*  checking that tables, either transformed or not, are visible at the correct time with the …
=> Add Spectrum buttons; change FOUC strategy

hub/scripts.js
Set page properties, including locale, cloud and category.
A new `fedPub` global object containing page details like language, country, locale, content category and cloud is created. Based on the object values additional attributes are added on the page or custom configurations are done.
- html `lang` property is set based on `language` value
- FEDS library locale is configured based on `locale` value
- TBD: FEDS library experience will be retrieved based on `content category` value
https://github.com/adobe/fedpub/issues/27
- SEO & LH; `lang` attribute is needed on the page
- A different navigation experience needs to be loaded based on locale and content category
Locally, using 2 different locales (article and index page).
=> feat(page): retrieve locale, cloud and category based on pare URL; update HTML lang.

head.html, hub/scripts.js
Add IMS library and enable Profile Menu
Profile Menu in FEDS library is enabled only when IMS library is loaded and configured. The PR handles loading and configuring IMS library and also deals with issues that appear when using `defer` and `async` for loading configuration and scripts.
https://github.com/adobe/fedpub/issues/25
Profile Menu is needed on all adobe.com pages
Locally
=> feat(Identity): Load IMS library and use Profile Menu

head.html
The `favicon` is located at https://fedpub--adobe.hlx.live/hub/icons/adobe.svg and not https://fedpub--adobe.hlx.live/icons/adobe.svg, causing some performance testing inconsistencies.
=> Correct favicon path

head.html
Serve custom fonts from Typekit instead of local folder. 
Small PR to load custom fonts directly from Typekit.
Akamai redirect rule does not include *hlx_fonts* folder. Recommendation was to load fonts from Typekit directly and keep consistency with other projects.
Locally - fonts are loaded from Typekit, there's no FOUC.
=> feat(fonts): Load fonts from Typekit

hub/scripts.js
Retrieve page details based on URL pattern
Update the logic to handle an additional use-case where the locale is not part of the URL. The code will parse the `location.pathname`, identify the part before "hub" and extract locale, cloud and category. The locale will be compared against a map of supported values.
The update will also send the correct language value to IMS.
https://github.com/adobe/fedpub/issues/27
Logic needs to support use-cases where locale is not part of the URL and set an implicit "en" language. 
Locally, with multiple URL patterns
=> feat(page): retrieve locale, cloud, category based on new URL pattern

head.html
The SEO team is requesting that a default value for the robots meta tag is added on all Fedpub pages. If a page requires a different value, it can be set from the Metadata section of the respective article.
https://github.com/adobe/fedpub/issues/45
The purpose of the Fedpub project revolves around SEO, thus we need to implement such SEO requests.
Locally, ensuring that the robots meta tag is added to the head section.
=> Add default robots meta tag (modularization)

head.html
The SEO team is requesting that a default value for the `robots` meta tag is added on all Fedpub pages. If a page requires a different value, it can be set from the Metadata section of the respective article.
https://github.com/adobe/fedpub/issues/45
The purpose of the Fedpub project revolves around SEO, thus we need to implement such SEO requests.
Locally, ensuring that the `robots` meta tag is added to the `head` section.
=> Add default robots meta tag

hub/scripts.js
This loads certain assets (such as the IMS, FEDS and Launch libraries) based on the current environment. This will allow us and authors to preview changes before they are published live.
https://github.com/adobe/fedpub/issues/42
To make it easier for all stakeholders to test and tweak changes before they reach the production environment.
On the local environment.
=> Load assets based on environment

hub/scripts.js
When loading Target, a `0.01` opacity is added to body until the functionality is loaded. Because of it, the content is not visible for some time; the issue is visible on all connection types.
Marketing Tech recommended disabling Target since it's not used on the page.
=> Disable Target

hub/scripts.js
Resolving https://jira.corp.adobe.com/browse/MWPW-82702
Description
Load the appropriate local navigation in `_draft` articles.
Context: the existing logic will fetch the locale/cloud/ category from URL, e.g. www.adobe.com/<locale>/<cloud>/<category>/hub/path/to/article.html and configure feds to load the experience `fedpub/cloud/category`. The code that sets the locale/ cloud/ category is available in https://github.com/adobe/fedpub/blob/master/hub/scripts.js#L417-L455
The request is to load the correct local navigation even when the author is working on a draft, e.g. www.adobe.com/_draft/<locale>/<cloud>/<category>/hub/path/to/article.htm
Pages to test:
Draft: https://localnav-ondrafts--fedpub--elaineskpt.hlx.page/_draft/de/documentcloud/acrobat/hub/how-to/document.html
Non Draft: …
=> Localnav Ondrafts

hub/scripts.js
Allow authors to insert promotion blades via metadata references
* metadata.xlsx reference - https://promotions--fedpub--narcis-radu.hlx.page/_draft/creativecloud/photography/hub/features/promo-example
* direct metadata reference - https://promotions--fedpub--narcis-radu.hlx.page/_draft/creativecloud/photography/hub/features/promo-example-direct
Locally
=> Add support for promotions

tools/translation/glaas.js, tools/translation/tracker.js, tools/translation/ui.js
File saving was broken for various reasons, main one was the name mapping: the real file name was used to create the handoffs on the GLaaS side. But the admin API has changed and the file name is filtered for URLs. No matching anymore.
Extracting the file name from the editURL until https://github.com/adobe/helix-admin/issues/281 is provided.
=> fix: save is broken

hub/scripts.js
In cases where we have a different folder structure, we want to read `window.fedpub.cloud` from the metadata instead of the URL.
https://jira.corp.adobe.com/browse/MWPW-90850
Closes https://github.com/adobe/fedpub/pull/100
We do not have consistent folder structures, thus need some extra logic to make stuff work. Also we have some pretty old code that's not needed anymore due to changes in the [helix pipeline](https://github.com/adobe/helix-pipeline-service/blob/main/src/steps/render.js)
Tested local and on branch.
https://read-cloud-from-metadata--fedpub--adobe.hlx.page/sign/hub/how-to/best-way-to-invoice-customers.html
window.fedpub = `{language: 'en', country: 'us', locale: 'en', cloud: 'documentcloud', category: 'sign'}`
https://read-cloud-from-metadata--fedpub--adobe.hlx.page/it/docum …
=> fix: read 'fedpub.cloud' from the document metadata

404.html
it turns out that having a redirect in a `404` can lead to problematic behavior for authors, when the load the `404` into the browser cache (eg. before publishing a page) it is not possible to remove it from the browser cache with a reload, as the URL has changed.
therefore it would be better to have the original URL remain in the browser location so the user can reload after publishing content.
https://404-fix--fedpub--adobe.hlx.live/404.html
i don't think this can really be tested on an actual `404`, as hlx3.page doesn't implement that behavior yet.
=> fix: remove redirecting 404 behavior

tools/sidekick/config.js
Authors currently end up on the generic outer CDN `main--fedpub--adobe.hlx.live` when clicking the "Live" button - which works, but does not reflect what is delivered in production.
https://custom-outer-cdn--fedpub--adobe.hlx3.page/creativecloud/photography/hub/guides/best-lens-for-headshot-photography
=> fix: use custom outer CDN hostname for live

helix-query.yaml
compare the index record generated in `main`:
https://admin.hlx.page/index/adobe/fedpub/main/creativecloud/design/hub/guides/add-orange-color-to-your-design
and with these changes:
https://admin.hlx.page/index/adobe/fedpub/remove-excludes/creativecloud/design/hub/guides/add-orange-color-to-your-design
=> fix: remove unnecessary excludes

helix-sitemap.yaml
or the lookup of alternate paths will not work
=> fix: alternate paths should start with a slash

helix-sitemap.yaml
denotes `en-US` as default language
=> fix: add default hreflang
